spring.application.name=k-project
server.port=${PORT:8080}
spring.config.import=optional:file:.env[.properties]
openai.api-key=${OPENAI_API_KEY:}
openai.base-url=https://api.openai.com/v1
openai.model=${OPENAI_MODEL:gpt-4.1-mini}
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.hikari.data-source-properties.sslmode=require
spring.datasource.hikari.data-source-properties.prepareThreshold=0
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA ?? (??? ?? ?? ? SQL ?? ??)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
